name: QQBotAuth
version: '${version}'
main: cn.cctstudio.qqbotauth.QQBotAuthPlugin
api-version: '1.21.11'
load: POSTWORLD
authors: [GouC, CCTStudio]
description: CCTStudio 官方 QQ 机器人账号验证插件
softdepend: [AuthMe, CCTSystem]
commands:
  qqbotauth:
    description: 打开 QQ 验证界面或管理 QQBotAuth
    usage: /qqbotauth [bind|unbind|status]
    aliases: [qqverify, qqyz]
    permission: qqbotauth.use
permissions:
  qqbotauth.use:
    description: 使用 QQ 验证功能
    default: true
  qqbotauth.admin:
    description: 管理 QQBotAuth
    default: op
